CREATE TABLE subscriber (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    line_user_id  VARCHAR(100) NOT NULL UNIQUE,
    display_name  VARCHAR(100),
    following     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP    NOT NULL
);

CREATE TABLE tracking_job (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subscriber_id  BIGINT      NOT NULL REFERENCES subscriber (id),
    provider_code  VARCHAR(30) NOT NULL,
    room_id        INTEGER     NOT NULL,
    target_number  INTEGER     NOT NULL,
    active         BOOLEAN     NOT NULL,
    end_reason     VARCHAR(20),
    created_at     TIMESTAMP   NOT NULL,
    ended_at       TIMESTAMP
);
CREATE INDEX idx_tracking_job_active_room ON tracking_job (provider_code, room_id, active);
CREATE INDEX idx_tracking_job_subscriber ON tracking_job (subscriber_id, active);

CREATE TABLE notification_rule (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subscriber_id  BIGINT    NOT NULL REFERENCES subscriber (id),
    threshold      INTEGER   NOT NULL,
    created_at     TIMESTAMP NOT NULL,
    CONSTRAINT uk_notification_rule UNIQUE (subscriber_id, threshold)
);

CREATE TABLE notification_history (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tracking_job_id  BIGINT    NOT NULL REFERENCES tracking_job (id),
    threshold        INTEGER   NOT NULL,
    pushed           BOOLEAN   NOT NULL,
    sent_at          TIMESTAMP NOT NULL,
    CONSTRAINT uk_notification_history UNIQUE (tracking_job_id, threshold)
);

CREATE TABLE room_status_history (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_code   VARCHAR(30) NOT NULL,
    room_id         INTEGER     NOT NULL,
    current_number  INTEGER     NOT NULL,
    doctor_name     VARCHAR(50),
    department      VARCHAR(50),
    exec_time       TIMESTAMP,
    created_at      TIMESTAMP   NOT NULL
);
CREATE INDEX idx_room_status_history_room_time ON room_status_history (provider_code, room_id, created_at);
