-- 推播結果：true 送達、false 失敗、null 未推播或尚未記錄
ALTER TABLE notification_history ADD COLUMN delivered BOOLEAN;

CREATE TABLE admin_audit_log (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_line_user_id  VARCHAR(100) NOT NULL,
    command             VARCHAR(200) NOT NULL,
    created_at          TIMESTAMP    NOT NULL
);
CREATE INDEX idx_admin_audit_log_created_at ON admin_audit_log (created_at);
